### ISSUE TITLE
how to generate headmask/headmask_13b_20.npy

### ISSUE THREAD

**Issue by jianfenglihg** [ZhangAIPI/YOPO_MLLM_Pruning#1]
Thank you for your excellent work. Could you please provide the specific details on how to generate headmask/headmask_13b_20.npy?

https://github.com/ZhangAIPI/YOPO_MLLM_Pruning/blob/a3328d61df0a696d6bffd681dc639eea6661ea9a/modeling_llama_prune.py#L329

**Comment by ZhangAIPI** [comment]
Hi, please check Sec 3.3 for algorithm details. The hyper-parameter alpha depends on the pruning ratio you expect, and we use a small-scale dataset to compute the ratio (6) for non-active attention head discovery. 

**We will provide the specific code implementation of this part later this week** and will remind you at that time.  (Sorry we are traveling now :))
