### ISSUE TITLE
Is there a practical guide for this method on Qwen2-VL and InternVL2.0?

### ISSUE THREAD

**Issue by yazheng0307** [ZhangAIPI/YOPO_MLLM_Pruning#2]
I want to use this method on Qwen2-VL and InternVL2.0. The current code only uses the method on LLAVA. How can it be used on the other two models?

**Comment by ZhangAIPI** [comment]
We will release the code for these models this weekend. Thanks for your interest:)

**Comment by ZhangAIPI** [comment]
Hi, we just released the code for Qwen and InternVL. Please check our updates on the README file!

**Comment by llvy21** [comment]
请问您有发布InternVL2.5以及Qwen2VL、InternVL更少参数量版本(2B、1B)的计划吗

**Comment by llvy21** [comment]
Hi, do you plan to release InternVL2.5 and fewer parameters Qwen2VL, InternVL (2B, 1B)?

**Comment by ZhangAIPI** [comment]
We will release them soon and will let you know when we release them.
