### ISSUE TITLE
如何实现的论文里提到的三步剪枝策略？

### ISSUE THREAD

**Issue by MstarLioning** [ZhangAIPI/YOPO_MLLM_Pruning#3]
您好！在阅读了您的论文YOPO之后希望能运行代码找到代码与论文的对应，但是看完Github项目后发现实现的代码像是指向了modeling_llama_prune.py，可是在YOPO的Github界面上似乎只有Inference、Training这两个部分的说明，没有指向modeling_llama_prune.py这个文件的环节。不知道这个问题是因为我错过了哪个步骤导致的？希望能得到您的指点！谢谢您！

**Comment by zhaowt61** [comment]
您好，请参见readme中install部分的第二个步骤：copy modeling_llama_prune.py 到指定路径以实现文中的四种剪枝策略

**Comment by MstarLioning** [comment]
谢谢您的回复！也就是说无论是在推理还是在训练过程中因为修改了Transformer库所以都会在原权重上实时处理各矩阵以实现四种剪枝策略的表现么？

**Comment by zhaowt61** [comment]
是的

**Comment by MstarLioning** [comment]
收到，谢谢您！实在不好意思问出这些基础的问题，再次感谢您帮助我解答疑惑！

**Comment by zhaowt61** [comment]
没关系，有任何问题都可以在issues里提出
