### ISSUE TITLE
实验结果对比

### ISSUE THREAD

**Issue by MstarLioning** [ZhangAIPI/YOPO_MLLM_Pruning#4]
您好，我是一名初学者，在尝试复现您的实验结果时，发现与论文中的结果有些小出入，不确定是否是由于我在某些步骤操作上存在失误。期待能得到您的回复，谢谢！
<img width="515" alt="0df5997fae969bd67c37b5949f1202f" src="https://github.com/user-attachments/assets/88c7637c-3092-4f3f-be9c-248b779d69b9" />
<img width="460" alt="b95aeff5ef53ccceff833051913994c" src="https://github.com/user-attachments/assets/067479c7-ea78-4b9d-9f53-577d59de9aaf" />

**Comment by MstarLioning** [comment]
配置采用的是llava-1.5-7b，Flops=12%

**Comment by zhaowt61** [comment]
您好，把截图里的三个accuracy求平均刚好是我们表格里的0.866

**Comment by MstarLioning** [comment]
收到，谢谢您！

**Comment by CoderXuans** [comment]
@MstarLioning 
你好，按照POPE进行评估的时候，popo.sh中的    --image-folder ./playground/data/eval/pope/val2014 \这一项只需要下载coco2014数据集中的[2014 Val. images [40K/6.2GB]]验证集吗？
