### ISSUE TITLE
直接运行bash infer.sh报错

### ISSUE THREAD

**Issue by donghong1** [ZhangAIPI/YOPO_MLLM_Pruning#5]
国内网络直接运行bash infer.sh会提示网络超时，请问这怎么解决呢？

**Comment by zhaowt61** [comment]
可以把截图发上来吗？

**Comment by donghong1** [comment]
加载完模型和preprocessor_config.json就开始报错了
<img width="932" alt="屏幕截图 2024-12-25 095139" src="https://github.com/user-attachments/assets/9e1f5f1e-98ee-4aa9-839b-e05f9436d5d0" />
<img width="937" alt="屏幕截图 2024-12-25 094904" src="https://github.com/user-attachments/assets/1ec860cb-ee12-416b-a304-b64d694347b0" />
![Uploading 屏幕截图 2024-12-25 095000.png…]()
![Uploading 屏幕截图 2024-12-25 095028.png…]()

**Comment by donghong1** [comment]
<img width="778" alt="屏幕截图 2024-12-25 095000" src="https://github.com/user-attachments/assets/5e52fd3b-83d1-4a03-8b9b-bdbc512e864c" />
<img width="943" alt="屏幕截图 2024-12-25 095028" src="https://github.com/user-attachments/assets/1ce2f8a6-3048-4ee7-adfe-43eb4e7d818e" />

**Comment by donghong1** [comment]
问题已解决，是由于下载模型的时候没有加载到huggingface的缓存目录里，而是自行指定了目录，导致加载不了缓存中的某些文件，国内网络又连不上huggingface导致的

**Comment by zhaowt61** [comment]
resolved
