### ISSUE TITLE
what 24 and 576  mean in code?

### ISSUE THREAD

**Issue by testpppppp** [ZhangAIPI/YOPO_MLLM_Pruning#6]
Hello author,
I read your code and find some const. and what does that mean and how  to get that?

https://github.com/ZhangAIPI/YOPO_MLLM_Pruning/blob/f0783f442781f9894be76bae99d7292eb9527b63/modeling_llama_prune.py#L801
 https://github.com/ZhangAIPI/YOPO_MLLM_Pruning/blob/f0783f442781f9894be76bae99d7292eb9527b63/LLaVA/scripts/v1_5/finetune_yopo.sh#L41

how to get the prompt_len ? 
same question for other model. 
Thanks!

**Comment by zhaowt61** [comment]
Hi, 24 is the height and width of image tokens. 576 = 24 x 24 is the number of image tokens. sprompt_len is the number of system prompt toke s. You need to print token_ids to get sprompt_len. Let me know if you have further questions.

**Comment by testpppppp** [comment]
Thanks for you reply.
But I find you use     --vision_tower openai/clip-vit-large-patch14-336 \
The patch size is 14, so for one image is 14*14?

**Comment by zhaowt61** [comment]
Hi, number of pathes is 24 = 336/14.
