### ISSUE TITLE
Could you upload the evaluation code to the GitHub repository?

### ISSUE THREAD

**Issue by donghong1** [ZhangAIPI/YOPO_MLLM_Pruning#7]
"I am new to this and struggling with evaluating the model's performance on the benchmark. Specifically, I am unsure how to properly use lmms_eval or llava_eval for evaluation after modifying the model. And I noticed that the paper does not include the test performance results of directly applying the pruning strategy without additional training .Could you please provide relevant  evaluation code?

**Comment by zhaowt61** [comment]
For evaluation, please refer to llava eval's and lmms-eval's env setup here respectively
https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md 
https://github.com/EvolvingLMMs-Lab/lmms-eval
Then replace LLaVA folder with ours and do step2 in install part of README (Copy our updated modeling_llama.py to transformer library)

For test performance results without fine-tuning, please see figure9 and figure10 in appendix.

**Comment by donghong1** [comment]
Hello, I still encountered some issues while using the steps you provided.The screenshot of the error is as follows:
<img width="696" alt="屏幕截图 2024-12-30 150457" src="https://github.com/user-attachments/assets/d95a9889-b4db-40b8-84cb-57025fbe35d7" />
Then I have located the problem here, and I would like to ask you about the meanings of these variables.
<img width="424" alt="屏幕截图 2024-12-30 151209" src="https://github.com/user-attachments/assets/464d8386-e0a5-465d-a7d6-9659cd40da86" />
Thank you!

**Comment by zhaowt61** [comment]
attncut_w: the radius of neighborhood attention, for example attncut_w=5 means for each image token, only the tokens within radius of 5 can be attended by it.
layercut_num: how many vision layers we want to preserve, others will be discarded.
headcut_num: how many vision heads we want to preserve
mlpcut_ratio: original_mlp_dimension/reduced_mlp_dimension
sprompt_len: token length of system prompt

**Comment by zhaowt61** [comment]
And please ensure you used the correct llava config file, eg. https://huggingface.co/zwt123home123/llava-1.5-13b-prune-zp12/blob/main/config.json#L45 
Let me know if you still cannot make it right. Thanks!

**Comment by donghong1** [comment]
Thanks for your generous help! I replaced the config.json in LLava ,and now it works properly.

**Comment by zhaowt61** [comment]
Good to know that, let us know if there is any further issues then I will reopen the ticket.
