### ISSUE TITLE
对论文可视化情况的请教

### ISSUE THREAD

**Issue by MstarLioning** [ZhangAIPI/YOPO_MLLM_Pruning#8]
您好，针对图5中可视化的layer-num_head构建的矩阵其中的值是直接提取的所有Token（文本和Prompt）的Attention值平均后的结果么？另想请问下为什么不提取最后一层Linear做可视化以表示模型对每个Token的关注程度呢？万分期待您的回复！谢谢！

<img width="590" alt="80003e63a82483eb97c0defac63707d" src="https://github.com/user-attachments/assets/1ceff5f3-c6f0-44fc-af49-f47b75916477" />

**Comment by ZhangAIPI** [comment]
(1) 是不同attention head平均后的结果
（2）我们这份工作的出发点还是想尽可能的利用所有的visual token从而减少对细粒度特征的忽视，但是从结构和计算的稀疏性上去做模型加速，所以全文一直在从结构方面做各种数值统计实验发现insight
        你说的是个很有意思也很值得去探索的点，与基于token dropping的策略不谋而合，可以参考下LLavA-PruMerge, FastV等工作的思路

**Comment by MstarLioning** [comment]
收到，谢谢您！
